# This is a basic workflow to help you get started with Actions

name: Build CN IPV4 list.

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GO111MODULE: on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3

      - name: Setup Rust environmet
        uses: dtolnay/rust-toolchain@stable

      - name: Install packages.
        run: |
          sudo apt-get update && sudo apt-get install -y bgpdump
          cargo install --vers 0.0.3 bgptools
          go install github.com/zhanhb/cidr-merger@v1.1.3
        shell: bash

      - name: Set variables
        run: |
          echo "PATH=$(go env GOPATH)/bin:${PATH}" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date -u +%Y.%m.%d)" >> $GITHUB_ENV
        shell: bash

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: code

      - name: Generate AS table
        run: curl -sSL ${{ secrets.OSS_URL }} > ASN_CN.txt
        shell: bash

      - name: Fetch bgp data.
        run: |
          wget -O rib.bz2 "http://archive.routeviews.org/dnszones/rib.bz2"

      - name: Dump bgp date.
        run: |
          echo "running bgpdump ..."
          bgpdump -m -O rib.txt rib.bz2
          echo "finish bgpdump"
        shell: bash

      - name: Generate China IPv4 list
        run: |
          cat ASN_CN.txt|xargs bgptools -b rib.txt|cidr-merger -s|grep -Fv ':' > CN_V4.txt
        shell: bash

      - name: Download and clean backup file
        run: |
          curl -sSL ${{ secrets.CNR_URL }} | grep -v '^#' > backup_routes.txt
          curl -sSL ${{ secrets.CNR_URL2 }} | grep -v '^#' > backup_routes2.txt
        shell: bash

      - name: Merge, deduplicate, and sort IPs
        run: |
          cat CN_V4.txt backup_routes.txt backup_routes2.txt | cidr-merger -s | sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n > CN_V4_merged.txt
        shell: bash

      - name: Generate cn.txt sha256 hash
        run: |
          sha256sum CN_V4_merged.txt > CN_V4_merged.txt.sha256sum
        shell: bash

      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release
          path: release

      - name: Git push assets to "release" branch
        run: |
          mv CN_V4_merged.txt release/CN_V4.txt
          mv CN_V4_merged.txt.sha256sum release/CN_V4.txt.sha256sum
          cd release
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          [ -n "$(git status -s)" ] && git commit -m "${{ env.RELEASE_NAME }}" || echo "Nothing to commit!"
          git push
        shell: bash
